import { AlertCircle, LoaderCircle, ShieldAlert, UserPlus, UsersRound } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "wouter";
import SiteShell from "@/components/SiteShell";
import { supabase, supabaseConfigured } from "@/lib/supabase";

type AllowlistRecord = { email: string; role: "instructor" | "administrator" | "super_admin"; created_at: string };
type Role = "student" | "instructor" | "administrator" | "super_admin";

export default function AccessControl() {
  const [role, setRole] = useState<Role | null>(null); const [entries, setEntries] = useState<AllowlistRecord[]>([]); const [loading, setLoading] = useState(true); const [email, setEmail] = useState(""); const [newRole, setNewRole] = useState<AllowlistRecord["role"]>("administrator"); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  async function load() { const { data, error: queryError } = await supabase.from("admin_allowlist").select("email, role, created_at").order("created_at", { ascending: false }); if (queryError) setError("Allowlist entries could not be loaded."); else setEntries((data ?? []) as AllowlistRecord[]); }
  useEffect(() => { if (!supabaseConfigured) { setLoading(false); return; } let active = true; async function bootstrap() { const { data: sessionData } = await supabase.auth.getSession(); if (!active || !sessionData.session) { setLoading(false); return; } const { data: profile } = await supabase.from("profiles").select("role").eq("id", sessionData.session.user.id).maybeSingle(); if (!active) return; setRole(profile?.role as Role ?? null); if (profile?.role === "super_admin") await load(); if (active) setLoading(false); } bootstrap(); return () => { active = false; }; }, []);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); setMessage(null); const normalized = email.trim().toLowerCase(); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(normalized)) { setError("Enter a valid institutional email address."); return; } setSaving(true); const { error: writeError } = await supabase.from("admin_allowlist").upsert({ email: normalized, role: newRole }, { onConflict: "email" }); if (writeError) setError(writeError.message); else { setMessage(`${normalized} has been allowlisted as ${newRole.replace("_", " ")}. Their role is assigned securely when they next authenticate.`); setEmail(""); await load(); } setSaving(false); }
  if (loading) return <SiteShell><div className="mx-auto flex min-h-[55vh] flex-col items-center justify-center"><LoaderCircle className="h-8 w-8 animate-spin text-wine" /><p className="mt-4 text-sm text-ink/60">Loading access-control authority…</p></div></SiteShell>;
  if (role !== "super_admin") return <SiteShell><section className="mx-auto flex min-h-[55vh] max-w-2xl flex-col items-center justify-center px-5 text-center"><ShieldAlert className="h-10 w-10 text-wine" /><h1 className="mt-5 font-serif text-4xl">Super-administrator authority required.</h1><p className="mt-3 leading-7 text-ink/65">Allowlisting changes future authenticated access. NIU reserves this operation for the highest institutional authority.</p><Link href="/portal" className="button-primary mt-7">Return to My NIU</Link></section></SiteShell>;
  return <SiteShell><section className="border-b border-wine/10 bg-canvas"><div className="mx-auto max-w-[1200px] px-5 py-12 sm:px-8"><p className="eyebrow">Access control</p><h1 className="mt-4 font-serif text-5xl tracking-[-0.04em]">Administrator allowlist.</h1><p className="mt-3 max-w-2xl leading-7 text-ink/65">Only super administrators can create or modify allowlist records. Changes are synchronized into an account’s approved NIU role at secure authentication time.</p></div></section><section className="mx-auto grid max-w-[1200px] gap-8 px-5 py-12 sm:px-8 lg:grid-cols-[.85fr_1.15fr]"><form onSubmit={submit} className="border border-wine/10 bg-white p-7 shadow-[0_16px_36px_rgba(29,25,21,0.05)]"><UserPlus className="h-6 w-6 text-wine" /><h2 className="mt-5 font-serif text-3xl">Add or update access</h2>{(error || message) && <div className={`mt-5 flex gap-3 border-l-4 p-4 text-sm ${error ? "border-wine bg-wine/5" : "border-emerald-700 bg-emerald-50 text-emerald-900"}`}><AlertCircle className={`h-5 w-5 shrink-0 ${error ? "text-wine" : "text-emerald-700"}`} />{error ?? message}</div>}<label className="mt-6 grid gap-2 text-sm font-semibold">Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="person@example.edu" className="border border-wine/20 px-3 py-3 font-normal outline-none focus:border-wine" /></label><label className="mt-4 grid gap-2 text-sm font-semibold">Approved role<select value={newRole} onChange={(event) => setNewRole(event.target.value as AllowlistRecord["role"])} className="border border-wine/20 bg-white px-3 py-3 font-normal outline-none focus:border-wine"><option value="instructor">Instructor</option><option value="administrator">Administrator</option><option value="super_admin">Super administrator</option></select></label><button disabled={saving} className="button-primary mt-6 w-full disabled:opacity-60">{saving ? "Saving…" : "Save allowlist entry"}</button></form><section className="border border-wine/10 bg-white p-7"><UsersRound className="h-6 w-6 text-wine" /><h2 className="mt-5 font-serif text-3xl">Current allowlist</h2>{entries.length === 0 ? <p className="mt-4 text-sm leading-6 text-ink/65">No additional staff accounts have been allowlisted. Existing super-administrator setup remains protected by database policy.</p> : <div className="mt-6 divide-y divide-wine/10">{entries.map((entry) => <div key={entry.email} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="font-semibold">{entry.email}</p><p className="mt-1 text-xs text-ink/55">Added {new Date(entry.created_at).toLocaleDateString()}</p></div><span className="rounded-full bg-canvas px-3 py-1 text-xs font-bold capitalize text-wine">{entry.role.replace("_", " ")}</span></div>)}</div>}</section></section></SiteShell>;
}
