import { AlertCircle, Clock3, LoaderCircle, Save, ShieldAlert } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "wouter";
import SiteShell from "@/components/SiteShell";
import { supabase, supabaseConfigured } from "@/lib/supabase";

type Role = "student" | "instructor" | "administrator" | "super_admin";
type Assignment = { id: string; title: string; due_at: string | null; late_submission_policy: { mode?: string; daily_penalty_percent?: number; grace_minutes?: number } | null; courses: { title: string }[] | null };
export default function AssignmentPolicies() {
  const [role, setRole] = useState<Role | null>(null); const [items, setItems] = useState<Assignment[]>([]); const [selectedId, setSelectedId] = useState(""); const [mode, setMode] = useState("accept_with_flag"); const [penalty, setPenalty] = useState("0"); const [grace, setGrace] = useState("0"); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const staff = role === "instructor" || role === "administrator" || role === "super_admin";
  async function load() { const { data, error: queryError } = await supabase.from("assignments").select("id,title,due_at,late_submission_policy,courses(title)").order("due_at", { ascending: true }).limit(200); if (queryError) setError("NIU could not load assignment policies."); else setItems((data ?? []) as Assignment[]); }
  useEffect(() => { if (!supabaseConfigured) { setLoading(false); return; } let active = true; async function init() { const { data: session } = await supabase.auth.getSession(); if (!active || !session.session) { setLoading(false); return; } const { data: profile } = await supabase.from("profiles").select("role").eq("id", session.session.user.id).maybeSingle(); if (!active) return; setRole(profile?.role as Role ?? null); if (profile?.role && profile.role !== "student") await load(); if (active) setLoading(false); } void init(); return () => { active = false; }; }, []);
  function choose(id: string) { setSelectedId(id); const current = items.find(item => item.id === id)?.late_submission_policy; setMode(current?.mode ?? "accept_with_flag"); setPenalty(String(current?.daily_penalty_percent ?? 0)); setGrace(String(current?.grace_minutes ?? 0)); }
  async function save(event: React.FormEvent) { event.preventDefault(); setError(null); setMessage(null); if (!selectedId) { setError("Choose an assignment first."); return; } const penaltyValue = Number(penalty); const graceValue = Number(grace); if (!Number.isFinite(penaltyValue) || penaltyValue < 0 || penaltyValue > 100 || !Number.isInteger(graceValue) || graceValue < 0) { setError("Use a penalty from 0–100 and a whole-number grace period of zero or more minutes."); return; } setSaving(true); const { error: updateError } = await supabase.from("assignments").update({ late_submission_policy: { mode, daily_penalty_percent: penaltyValue, grace_minutes: graceValue } }).eq("id", selectedId); if (updateError) setError(updateError.message); else { setMessage("Late-submission policy saved to the protected assignment record."); await load(); } setSaving(false); }
  if (loading) return <SiteShell><div className="grid min-h-[55vh] place-items-center"><LoaderCircle className="h-8 w-8 animate-spin text-wine" /></div></SiteShell>;
  if (!staff) return <SiteShell><section className="mx-auto flex min-h-[55vh] max-w-2xl flex-col items-center justify-center px-5 text-center"><ShieldAlert className="h-10 w-10 text-wine" /><h1 className="mt-5 font-serif text-4xl">Academic staff authority required.</h1><Link href={role ? "/portal" : "/signin"} className="button-primary mt-7">{role ? "Return to My NIU" : "Sign in to NIU"}</Link></section></SiteShell>;
  return <SiteShell><section className="border-b border-wine/10 bg-canvas"><div className="mx-auto max-w-[1000px] px-5 py-12 sm:px-8"><p className="eyebrow">Assignment policy</p><h1 className="mt-4 font-serif text-5xl tracking-[-0.04em]">Set recognised late-submission rules.</h1><p className="mt-3 max-w-3xl leading-7 text-ink/65">Each policy is retained on the assignment record. It provides a governed basis for review and grading; staff must still apply any adjustment through the protected grade workflow.</p></div></section><section className="mx-auto max-w-[1000px] px-5 py-12 sm:px-8"><form onSubmit={save} className="border border-wine/10 bg-white p-7 shadow-[0_16px_36px_rgba(29,25,21,0.05)]"><Clock3 className="h-6 w-6 text-wine" /><h2 className="mt-4 font-serif text-3xl">Configure an assignment</h2>{(error || message) && <p className={`mt-5 flex gap-2 border-l-4 p-4 text-sm ${error ? "border-wine bg-wine/5" : "border-emerald-700 bg-emerald-50 text-emerald-900"}`}><AlertCircle className="h-5 w-5 shrink-0" />{error ?? message}</p>}<label className="mt-6 grid gap-2 text-sm font-semibold">Assignment<select value={selectedId} onChange={event => choose(event.target.value)} className="border border-wine/20 bg-white px-3 py-3 font-normal"><option value="">Choose an assignment</option>{items.map(item => <option key={item.id} value={item.id}>{item.courses?.[0]?.title ?? "NIU course"} · {item.title}</option>)}</select></label><label className="mt-4 grid gap-2 text-sm font-semibold">Late-submission handling<select value={mode} onChange={event => setMode(event.target.value)} className="border border-wine/20 bg-white px-3 py-3 font-normal"><option value="accept_with_flag">Accept and flag for staff review</option><option value="accept_with_penalty">Accept with daily penalty</option><option value="reject_after_grace">Reject after the grace period</option></select></label><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">Daily penalty percentage<input type="number" min="0" max="100" value={penalty} onChange={event => setPenalty(event.target.value)} disabled={mode !== "accept_with_penalty"} className="border border-wine/20 px-3 py-3 font-normal disabled:bg-canvas" /></label><label className="grid gap-2 text-sm font-semibold">Grace period (minutes)<input type="number" min="0" step="1" value={grace} onChange={event => setGrace(event.target.value)} className="border border-wine/20 px-3 py-3 font-normal" /></label></div><button disabled={saving} className="button-primary mt-6"><Save className="h-4 w-4" />{saving ? "Saving…" : "Save assignment policy"}</button></form></section></SiteShell>;
}
