import { AlertCircle, FilePenLine, LoaderCircle, RefreshCw, ShieldAlert } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "wouter";
import SiteShell from "@/components/SiteShell";
import { supabase, supabaseConfigured } from "@/lib/supabase";

type Role = "student" | "instructor" | "administrator" | "super_admin";
type Certificate = { id: string; credential_number: string | null; credential_title: string | null; final_score: number | null; issued_at: string | null; profiles: { display_name: string | null; legal_name: string | null }[] | null; certificate_programs: { name: string }[] | null };
export default function CredentialReissue() {
  const [allowed, setAllowed] = useState(false); const [role, setRole] = useState<Role | null>(null); const [certificates, setCertificates] = useState<Certificate[]>([]); const [loading, setLoading] = useState(true); const [working, setWorking] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  async function load() { const { data, error: queryError } = await supabase.from("certificates").select("id,credential_number,credential_title,final_score,issued_at,profiles(display_name,legal_name),certificate_programs(name)").eq("status", "active").order("issued_at", { ascending: false }).limit(100); if (queryError) setError("NIU could not load active credentials for correction."); else setCertificates((data ?? []) as Certificate[]); }
  useEffect(() => { if (!supabaseConfigured) { setLoading(false); return; } let active = true; async function init() { const { data: sessionData } = await supabase.auth.getSession(); if (!active || !sessionData.session) { setLoading(false); return; } const { data: profile } = await supabase.from("profiles").select("role").eq("id", sessionData.session.user.id).maybeSingle(); if (!active || !profile) { setLoading(false); return; } setRole(profile.role as Role); const { data: registrar } = await supabase.from("profile_role_assignments").select("institutional_role").eq("profile_id", sessionData.session.user.id).eq("institutional_role", "registrar").maybeSingle(); const permitted = profile.role === "administrator" || profile.role === "super_admin" || Boolean(registrar); setAllowed(permitted); if (permitted) await load(); if (active) setLoading(false); } void init(); return () => { active = false; }; }, []);
  async function reissue(certificate: Certificate) { setError(null); setMessage(null); const reason = window.prompt("State the correction/reissue reason (minimum 3 characters):"); if (!reason || reason.trim().length < 3) { setError("A reissue reason of at least three characters is required."); return; } const scoreText = window.prompt("Replacement final score (leave unchanged to keep the current score):", certificate.final_score?.toString() ?? ""); if (scoreText === null) return; const score = scoreText.trim() ? Number(scoreText) : null; if (score !== null && (!Number.isFinite(score) || score < 0 || score > 100)) { setError("A replacement score must be between 0 and 100."); return; } if (!window.confirm("Reissue this credential? The existing credential will be marked superseded and a new verifiable credential number will be created.")) return; setWorking(certificate.id); const { data, error: rpcError } = await supabase.rpc("niu_reissue_certificate", { target_certificate_id: certificate.id, target_reason: reason.trim(), target_final_score: score }); if (rpcError || !data?.[0]) setError(rpcError?.message ?? "NIU could not reissue this credential."); else { setMessage(`Replacement credential ${data[0].credential_number} was issued. The original is retained as superseded history.`); await load(); } setWorking(null); }
  if (loading) return <SiteShell><div className="grid min-h-[55vh] place-items-center"><LoaderCircle className="h-8 w-8 animate-spin text-wine" /></div></SiteShell>;
  if (!allowed) return <SiteShell><section className="mx-auto flex min-h-[55vh] max-w-2xl flex-col items-center justify-center px-5 text-center"><ShieldAlert className="h-10 w-10 text-wine" /><h1 className="mt-5 font-serif text-4xl">Registrar authority required.</h1><p className="mt-3 leading-7 text-ink/65">Certificate correction and reissue requires an NIU administrator or an assigned registrar.</p><Link href={role ? "/portal" : "/signin"} className="button-primary mt-7">{role ? "Return to My NIU" : "Sign in to NIU"}</Link></section></SiteShell>;
  return <SiteShell><section className="border-b border-wine/10 bg-canvas"><div className="mx-auto max-w-[1200px] px-5 py-12 sm:px-8"><p className="eyebrow">Credential corrections</p><h1 className="mt-4 font-serif text-5xl tracking-[-0.04em]">Controlled certificate reissue.</h1><p className="mt-3 max-w-3xl leading-7 text-ink/65">Use only for a genuine correction. NIU retains the original credential as superseded history and creates a new credential number for the replacement record.</p></div></section><section className="mx-auto max-w-[1200px] px-5 py-10 sm:px-8">{(error || message) && <p className={`mb-6 flex gap-2 border-l-4 p-4 text-sm ${error ? "border-wine bg-wine/5" : "border-emerald-700 bg-emerald-50 text-emerald-900"}`}><AlertCircle className="h-5 w-5 shrink-0" />{error ?? message}</p>}<Link href="/registrar" className="button-secondary mb-6">Return to registrar workspace</Link><div className="overflow-hidden border border-wine/10 bg-white"><div className="p-7"><FilePenLine className="h-6 w-6 text-wine" /><h2 className="mt-4 font-serif text-3xl">Active credentials</h2></div><div className="divide-y divide-wine/10">{certificates.length ? certificates.map(certificate => <article key={certificate.id} className="flex flex-col gap-4 p-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-mono text-xs text-wine">{certificate.credential_number}</p><h3 className="mt-2 font-serif text-2xl">{certificate.credential_title ?? certificate.certificate_programs?.[0]?.name ?? "NIU certificate"}</h3><p className="mt-2 text-sm text-ink/60">{certificate.profiles?.[0]?.display_name || certificate.profiles?.[0]?.legal_name || "Protected learner"} · issued {certificate.issued_at ? new Date(certificate.issued_at).toLocaleDateString() : "—"} · score {certificate.final_score ?? "—"}</p></div><button disabled={working === certificate.id} onClick={() => void reissue(certificate)} className="button-primary shrink-0"><RefreshCw className="h-4 w-4" />{working === certificate.id ? "Reissuing…" : "Correct / reissue"}</button></article>) : <p className="p-8 text-center text-sm text-ink/60">No active credentials are currently available for correction.</p>}</div></div></section></SiteShell>;
}
