import { ArrowRight, BookOpen, CalendarDays, HelpCircle, Landmark, Mail, Scale, ShieldCheck, Sparkles } from "lucide-react";
import { Link, useLocation } from "wouter";
import SiteShell from "@/components/SiteShell";
type IconType = typeof Landmark;
type InfoConfig = { eyebrow: string; title: string; copy: string; icon: IconType; panels: [string, string][] };
const pages: Record<string, InfoConfig> = {
  "/about": { eyebrow:"About NIU", title:"An institution built for accountable digital learning.", copy:"Nova International University is establishing a responsible foundation for certificate education: academic structure, controlled content publication, measurable learning, and verifiable credential records.", icon:Landmark, panels:[["Certificate focus","NIU currently supports certificate programs only. Degree enrollment is deliberately disabled."],["Institutional clarity","Academic structures, policies, and records are designed to support legitimate future expansion without making unverified claims."],["Responsible administration","Authorized staff manage content, learner records, approvals, and audit-linked actions."]] },
  "/founder": { eyebrow:"Leadership", title:"Founder and President", copy:"Akin S. Sokpah is identified as NIU’s Founder and President. Biographical and professional information is published only when authorised and verified by the institution.", icon:Landmark, panels:[["Institutional leadership","A governed home for approved leadership communication and institutional policy."],["Credential stewardship","Certificate issuance includes a president identifier only after administrative approval."],["Verified information","NIU does not publish unsupported qualifications, affiliations, partnerships, or recognition claims."]] },
  "/mission": { eyebrow:"Mission & vision", title:"Learning designed to be clear, measurable, and useful.", copy:"NIU’s learning environment is designed around structured certificate pathways, transparent requirements, meaningful assessment, and records that can be responsibly verified.", icon:Sparkles, panels:[["Mission","Support accessible, organised, and accountable certificate learning."],["Vision","Build a durable digital academic foundation prepared for legitimate institutional evolution."],["Values","Clarity, care, integrity, accessibility, privacy, and responsible innovation guide platform design."]] },
  "/values": { eyebrow:"Institutional values", title:"Trust is a design requirement, not a decorative promise.", copy:"Every layer of NIU—from public programme discovery to protected learning records—is intended to make expectations visible and consequential actions traceable.", icon:ShieldCheck, panels:[["Integrity","No unsupported academic recognition, accreditation, faculty, or partnership claims are published."],["Accessibility","Learning experiences are designed for keyboard access, readable contrast, captions, transcripts, and responsive devices."],["Privacy","Public credential verification is limited to necessary record fields and protected institutional records remain private."]] },
  "/schools": { eyebrow:"Academic structure", title:"Schools and departments are managed as living institutional records.", copy:"NIU administrators can establish schools, departments, faculty assignments, programmes, and courses through authorised workflows. Public listings appear only after publication.", icon:Landmark, panels:[["Schools","Schools provide the organisational level for related departments and academic activity."],["Departments","Departments connect approved programmes, courses, faculty profiles, and accountable leadership."],["Future-ready structure","The structure can evolve without activating degree enrolment or making degree-awarding claims."]] },
  "/admissions": { eyebrow:"Admissions", title:"Begin with a published certificate pathway.", copy:"NIU admissions are connected to actual published certificate programmes and their approved entry requirements. No degree enrolment flow is enabled.", icon:BookOpen, panels:[["Choose a programme","Review published certificate objectives, duration, requirements, and learning outcomes."],["Create an account","Use the approved NIU authentication route to establish a protected learner profile."],["Enrol when available","Programme enrolment becomes available only through an authorized academic or administrative workflow."]] },
  "/resources": { eyebrow:"Student resources", title:"Learning support, organised around the record that matters.", copy:"NIU is preparing a digital library, help resources, accessible materials, and personal learning-record access. Resources are published through governed workflows.", icon:BookOpen, panels:[["Digital library","Searchable resources are designed to respect copyright and make legitimate materials discoverable."],["Accessible learning","Equivalent formats, captions, transcripts, alt text, and readable materials are part of the learning standard."],["Support","Technical, academic, and administrative support requests are designed to be trackable through protected tickets."]] },
  "/calendar": { eyebrow:"Academic calendar", title:"A clear view of the dates that shape learning.", copy:"Published calendar events present relevant enrolment periods, course dates, assessments, examinations, events, and certificate milestones for their intended audiences.", icon:CalendarDays, panels:[["Relevant visibility","Students see dates connected to their programmes and courses; staff see dates related to their responsibilities."],["Controlled publication","Calendar entries are published through authorized academic administration."],["Respectful planning","Events, holidays, assessments, and certificate activity are managed as explicit records."]] },
  "/help": { eyebrow:"Help center", title:"Practical support for every stage of the NIU experience.", copy:"The NIU help center is designed for technical access, learning-platform support, academic questions, and institutional administration. Authenticated students can track support requests in their protected account.", icon:HelpCircle, panels:[["Technical support","Get help with account access, browser compatibility, accessibility, and platform navigation."],["Academic support","Ask questions about programme structure, course access, learning requirements, and assessment workflows."],["Accountable follow-up","Support tickets are designed to retain status and appropriate access controls."]] },
  "/faqs": { eyebrow:"Frequently asked questions", title:"Direct answers to the questions that matter.", copy:"NIU’s public information distinguishes certificate education from regulated degree pathways and avoids unverified representations.", icon:HelpCircle, panels:[["Does NIU offer degrees?","No. NIU currently offers certificate programs only, and degree enrollment is not enabled."],["How are credentials verified?","Credential numbers and QR links are checked against the official NIU credential database."],["What information is public?","Verification presents minimal approved record fields. Private student information and academic records are not public."]] },
  "/policies": { eyebrow:"Policies", title:"Policies that are editable, published, and accountable.", copy:"NIU policy pages are designed for authorized publication and dated records covering academic integrity, assessment, examinations, grading, conduct, privacy, accessibility, appeals, complaints, and certificate stewardship.", icon:Scale, panels:[["Academic integrity","Controls focus on reasonable safeguards, secure submissions, and audit trails—not surveillance or impossible claims of perfect prevention."],["Privacy & accessibility","Policies address profile controls, restricted records, accessible materials, and fair participation."],["Credential stewardship","Certificate issuance and revocation are formal processes with authorization, reasons, timestamps, and history."]] },
  "/contact": { eyebrow:"Contact NIU", title:"Connect through official institutional channels.", copy:"Official address, telephone, email, and website fields are administratively configurable. They appear once verified institutional contact information is published.", icon:Mail, panels:[["Admissions enquiries","Ask about published certificate programmes and approved admission pathways."],["Learner support","Get help with existing account access and learning-platform questions."],["Institutional contact","Official contact details are intentionally not fabricated; administrators publish verified details through NIU settings."]] },
};
export default function InfoPage() { const [location] = useLocation(); const config = pages[location] ?? pages["/about"]; const Icon = config.icon; return <SiteShell><section className="border-b border-wine/10 bg-canvas"><div className="mx-auto max-w-[1440px] px-5 py-16 sm:px-8 lg:px-12 lg:py-22"><div className="max-w-3xl"><p className="eyebrow">{config.eyebrow}</p><h1 className="mt-5 font-serif text-5xl leading-[1.02] tracking-[-0.04em] text-ink sm:text-6xl">{config.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-ink/70">{config.copy}</p></div></div></section><section className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-12 lg:py-18"><div className="grid gap-5 md:grid-cols-3">{config.panels.map(([title, body]) => <article key={title} className="bg-white p-7 shadow-[0_16px_36px_rgba(29,25,21,0.06)]"><Icon className="h-6 w-6 text-wine" /><h2 className="mt-6 font-serif text-2xl">{title}</h2><p className="mt-3 text-sm leading-6 text-ink/65">{body}</p></article>)}</div><div className="mt-12 flex flex-col justify-between gap-5 border-t-2 border-wine bg-wine/5 p-7 sm:flex-row sm:items-center"><p className="max-w-2xl text-sm leading-6 text-ink/70">Need an institution-specific answer? NIU public content is published from authorised records. Contact support for help with existing learning or credential records.</p><Link href="/help" className="inline-flex shrink-0 items-center gap-2 text-sm font-bold text-wine hover:text-ink">Visit help center <ArrowRight className="h-4 w-4" /></Link></div></section></SiteShell>; }
