import { AlertCircle, Building2, CalendarDays, FileCheck2, LoaderCircle, ShieldAlert } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import SiteShell from "@/components/SiteShell";
import { supabase, supabaseConfigured } from "@/lib/supabase";

type Role = "student" | "instructor" | "administrator" | "super_admin";
type RecordType = "school" | "department" | "calendar_event";
type InstitutionalRecord = { id: string; label: string; detail: string; status: string; updated_at?: string; starts_at?: string };
const recordTypes: Array<{ value: RecordType; label: string; icon: typeof Building2 }> = [{ value: "school", label: "School", icon: Building2 }, { value: "department", label: "Department", icon: Building2 }, { value: "calendar_event", label: "Calendar event", icon: CalendarDays }];
const statuses = ["draft", "review", "approved", "published", "archived"] as const;

export default function InstitutionalPublication() {
  const [role, setRole] = useState<Role | null>(null); const [records, setRecords] = useState<Record<"school" | "department" | "calendar_event", InstitutionalRecord[]>>({ school: [], department: [], calendar_event: [] }); const [recordType, setRecordType] = useState<RecordType>("school"); const [recordId, setRecordId] = useState(""); const [status, setStatus] = useState<(typeof statuses)[number]>("review"); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const allowed = role === "administrator" || role === "super_admin";
  const options = records[recordType]; const selected = useMemo(() => options.find(item => item.id === recordId), [options, recordId]);
  async function load() { const [schools, departments, events] = await Promise.all([supabase.from("schools").select("id,name,code,status,updated_at").order("updated_at", { ascending: false }).limit(250), supabase.from("departments").select("id,name,code,status,updated_at").order("updated_at", { ascending: false }).limit(250), supabase.from("academic_calendar_events").select("id,title,event_type,status,starts_at").order("starts_at", { ascending: false }).limit(250)]); if (schools.error || departments.error || events.error) { setError("NIU could not load institutional publication records for this account."); return; } setRecords({ school: (schools.data ?? []).map(item => ({ id: item.id, label: item.name, detail: item.code, status: item.status, updated_at: item.updated_at })), department: (departments.data ?? []).map(item => ({ id: item.id, label: item.name, detail: item.code, status: item.status, updated_at: item.updated_at })), calendar_event: (events.data ?? []).map(item => ({ id: item.id, label: item.title, detail: item.event_type, status: item.status, starts_at: item.starts_at })) }); }
  useEffect(() => { if (!supabaseConfigured) { setLoading(false); return; } let active = true; async function initialize() { const { data: sessionData } = await supabase.auth.getSession(); if (!active || !sessionData.session) { setLoading(false); return; } const { data: profile } = await supabase.from("profiles").select("role").eq("id", sessionData.session.user.id).maybeSingle(); if (!active) return; setRole((profile?.role as Role) ?? null); if (profile?.role === "administrator" || profile?.role === "super_admin") await load(); if (active) setLoading(false); } void initialize(); return () => { active = false; }; }, []);
  function changeType(next: RecordType) { setRecordType(next); setRecordId(""); setStatus("review"); setNotice(null); setError(null); }
  async function save(event: React.FormEvent) { event.preventDefault(); setError(null); setNotice(null); if (!recordId) { setError("Choose an existing NIU record before recording a publication decision."); return; } setSaving(true); const { error: writeError } = await supabase.rpc("niu_update_institutional_publication", { target_record_type: recordType, target_record_id: recordId, target_status: status }); if (writeError) setError(writeError.message); else { setNotice(`The ${recordType.replace("_", " ")} is now ${status}. NIU recorded the administrator, timestamp, and audit event.`); await load(); } setSaving(false); }
  if (loading) return <SiteShell><div className="grid min-h-[55vh] place-items-center"><LoaderCircle className="h-8 w-8 animate-spin text-wine" /></div></SiteShell>;
  if (!allowed) return <SiteShell><section className="mx-auto flex min-h-[55vh] max-w-2xl flex-col items-center justify-center px-5 text-center"><ShieldAlert className="h-10 w-10 text-wine" /><h1 className="mt-5 font-serif text-4xl">Administrator authority required.</h1><p className="mt-3 leading-7 text-ink/65">Only NIU administrators can approve, publish, or archive institutional structure and calendar records.</p><Link href={role ? "/portal" : "/signin"} className="button-primary mt-7">{role ? "Return to My NIU" : "Sign in to NIU"}</Link></section></SiteShell>;
  const TypeIcon = recordTypes.find(item => item.value === recordType)?.icon ?? FileCheck2;
  return <SiteShell><section className="border-b border-wine/10 bg-canvas"><div className="mx-auto max-w-[1200px] px-5 py-12 sm:px-8"><p className="eyebrow">Institutional publication</p><h1 className="mt-4 font-serif text-5xl tracking-[-0.04em]">Publish institutional records with accountability.</h1><p className="mt-3 max-w-4xl leading-7 text-ink/65">Academic staff can create genuine draft records. This administrator-only control records review, publication, archival, and the accompanying NIU audit event. Existing calendar events retain their public visibility during the upgrade.</p></div></section><section className="mx-auto max-w-[1200px] px-5 py-10 sm:px-8"><div className="flex flex-wrap gap-3">{recordTypes.map(item => <button key={item.value} onClick={() => changeType(item.value)} className={recordType === item.value ? "button-primary" : "button-secondary"}>{item.label}</button>)}</div><form onSubmit={save} className="mt-7 max-w-3xl border border-wine/10 bg-white p-7 shadow-[0_16px_36px_rgba(29,25,21,0.05)]"><TypeIcon className="h-6 w-6 text-wine" /><h2 className="mt-4 font-serif text-3xl">Record a {recordType.replace("_", " ")} decision</h2>{(notice || error) && <p className={`mt-5 flex gap-2 border-l-4 p-4 text-sm ${error ? "border-wine bg-wine/5" : "border-emerald-700 bg-emerald-50 text-emerald-900"}`}><AlertCircle className="h-5 w-5 shrink-0" />{error ?? notice}</p>}<label className="mt-6 grid gap-2 text-sm font-semibold">Existing record<select value={recordId} onChange={event => { setRecordId(event.target.value); const next = options.find(item => item.id === event.target.value); if (next && statuses.includes(next.status as (typeof statuses)[number])) setStatus(next.status as (typeof statuses)[number]); }} className="border border-wine/20 bg-white px-3 py-3 font-normal"><option value="">Choose a record</option>{options.map(item => <option key={item.id} value={item.id}>{item.label} · {item.detail} · {item.status}</option>)}</select></label><label className="mt-4 grid gap-2 text-sm font-semibold">New review stage<select value={status} onChange={event => setStatus(event.target.value as (typeof statuses)[number])} className="border border-wine/20 bg-white px-3 py-3 font-normal">{statuses.map(value => <option key={value} value={value}>{value[0].toUpperCase() + value.slice(1)}</option>)}</select><span className="font-normal text-xs leading-5 text-ink/55">A published school or department can appear in public NIU discovery. A published calendar event can appear in the public academic calendar. Archived records remain retained but are no longer public.</span></label>{selected && <p className="mt-5 border-l-4 border-gold bg-gold/10 p-4 text-sm leading-6 text-ink/80"><b>Current state:</b> {selected.status}. This decision will retain the record and append a new audit event.</p>}<button disabled={saving} className="button-primary mt-6">{saving ? "Recording…" : "Save accountable decision"}</button></form></section></SiteShell>;
}
