import { ArrowLeft, ArrowRight, Award, CheckCircle2, Clock3, LoaderCircle } from "lucide-react";
import { Link, useRoute } from "wouter";
import SiteShell from "@/components/SiteShell";
import { trpc } from "@/lib/trpc";

export default function ProgramDetails() {
  const [, params] = useRoute("/programs/:id");
  const result = trpc.catalog.getPublishedProgram.useQuery({ id: params?.id ?? "00000000-0000-0000-0000-000000000000" }, { enabled: Boolean(params?.id), retry: false });
  if (result.isLoading) return <SiteShell><div className="mx-auto flex min-h-[55vh] flex-col items-center justify-center"><LoaderCircle className="h-8 w-8 animate-spin text-wine" /><p className="mt-4 text-sm text-ink/60">Loading published program…</p></div></SiteShell>;
  if (result.isError || !result.data) return <SiteShell><section className="mx-auto flex min-h-[55vh] max-w-2xl flex-col items-center justify-center px-5 text-center"><h1 className="font-serif text-4xl">Published program not found.</h1><Link href="/programs" className="button-primary mt-7">Return to programs</Link></section></SiteShell>;

  const program = result.data;
  const outcomes = Array.isArray(program.learning_outcomes) ? program.learning_outcomes : [];
  const linkedCourses = (program.program_courses ?? []).sort((a, b) => a.position - b.position).map((link) => ({ ...link, course: link.courses?.[0] ?? null }));

  return <SiteShell><section className="border-b border-wine/10 bg-canvas"><div className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-12"><Link href="/programs" className="inline-flex items-center gap-2 text-sm font-bold text-wine"><ArrowLeft className="h-4 w-4" />All programs</Link><p className="mt-8 eyebrow">{program.code} · Certificate program</p><h1 className="mt-4 max-w-4xl font-serif text-5xl tracking-[-0.04em] sm:text-6xl">{program.name}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-ink/70">{program.description}</p><div className="mt-8 flex flex-wrap gap-5 text-sm text-ink/65"><span className="flex items-center gap-2"><Clock3 className="h-4 w-4 text-wine" />{program.duration_hours} learning hours</span><span className="capitalize">{program.difficulty}</span><span>Required score: {program.required_score}%</span></div></div></section><section className="mx-auto grid max-w-[1440px] gap-8 px-5 py-12 sm:px-8 lg:grid-cols-2 lg:px-12"><div className="border border-wine/10 bg-white p-7"><Award className="h-6 w-6 text-wine" /><h2 className="mt-5 font-serif text-3xl">Certificate pathway</h2><p className="mt-3 leading-7 text-ink/65">This is a certificate-only program. NIU does not enable degree enrollment through this program or its associated courses.</p><Link href="/signin" className="button-primary mt-7">Sign in for eligibility access <ArrowRight className="h-4 w-4" /></Link></div><div className="border border-wine/10 bg-white p-7"><CheckCircle2 className="h-6 w-6 text-wine" /><h2 className="mt-5 font-serif text-3xl">Learning outcomes</h2><ul className="mt-5 grid gap-3 text-sm leading-6 text-ink/70">{outcomes.length > 0 ? outcomes.map((outcome, index) => <li key={index} className="flex gap-3"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-wine" />{String(outcome)}</li>) : <li>Published learning outcomes will appear when authorised academic staff completes program publication.</li>}</ul></div><div className="lg:col-span-2"><p className="eyebrow">Program structure</p><h2 className="mt-2 font-serif text-3xl">Published course sequence</h2><div className="mt-5 grid gap-4">{linkedCourses.length === 0 ? <div className="border border-dashed border-wine/25 bg-canvas p-8 text-sm text-ink/65">Course sequence will appear after program-course relationships are published.</div> : linkedCourses.map((link) => <article key={link.position} className="flex flex-col justify-between gap-4 border border-wine/10 bg-white p-5 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-wine">{link.is_required ? "Required course" : "Elective course"}</p><h3 className="mt-2 font-serif text-2xl">{link.course?.title ?? "Course"}</h3><p className="mt-2 text-sm text-ink/65">{link.course?.description}</p></div>{link.course?.slug && <Link href={`/courses/${link.course.slug}`} className="button-secondary">View course</Link>}</article>)}</div></div></section></SiteShell>;
}
