import { AlertCircle, ArrowRight, BadgeCheck, BarChart3, BookOpenText, ClipboardCheck, FileCheck2, FolderCog, LoaderCircle, ShieldAlert, UsersRound } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link, useRoute } from "wouter";
import type { Session } from "@supabase/supabase-js";
import type { CoreNiuRole, DashboardKey, InstitutionalRole } from "@shared/roleDashboards";
import { canAccessDashboard } from "@shared/roleDashboards";
import SiteShell from "@/components/SiteShell";
import { supabase, supabaseConfigured } from "@/lib/supabase";

type Profile = { role: CoreNiuRole; display_name: string | null; legal_name: string | null };
type DashboardConfig = { label: string; title: string; description: string; cards: Array<{ icon: typeof BookOpenText; title: string; body: string }> };

const dashboards: Record<DashboardKey, DashboardConfig> = {
  faculty: { label: "Faculty workspace", title: "Teach from an accountable course record.", description: "Manage your authorised academic work without approving your own credentials. Course, assessment, learner, and discussion records remain scoped to approved responsibilities.", cards: [{ icon: BookOpenText, title: "Assigned course work", body: "Published and draft courses assigned to your role appear here when academic assignments are recorded." }, { icon: ClipboardCheck, title: "Assessment review", body: "Grading queues, manual-response review, feedback, and authorised attempt records appear here when assigned." }, { icon: BarChart3, title: "Course learning insights", body: "Engagement and performance data are limited to your authorised instructional scope." }] },
  registrar: { label: "Registrar workspace", title: "Steward learner records and credential decisions.", description: "Review authorised records, certificate candidates, credentials, and status history. Certificate issuance remains subject to controlled review and audit evidence.", cards: [{ icon: FileCheck2, title: "Certificate candidates", body: "Eligible learners awaiting registrar or administrative review appear here when program requirements are verified." }, { icon: BadgeCheck, title: "Credential registry", body: "Active, revoked, and superseded credential status records are managed through explicit authorised actions." }, { icon: UsersRound, title: "Academic records", body: "Learner records, enrollment history, and approved certificates are visible only within registrar authority." }] },
  administrator: { label: "Administrator workspace", title: "Govern the institution without bypassing its controls.", description: "Manage approved institutional settings, access governance, academic structure, content publication, and audit-ready operational records.", cards: [{ icon: FolderCog, title: "Institutional structure", body: "Create schools, departments, programmes, and academic units through controlled institutional records." }, { icon: ShieldAlert, title: "Access & permissions", body: "Maintain allowlists, operational role assignments, and permission policies without granting browser-only authority." }, { icon: BarChart3, title: "Operational oversight", body: "Review publication states, certificate queues, audit-linked activity, and institutional reports when records are available." }] },
};

export default function RoleDashboard() {
  const [, params] = useRoute("/dashboard/:dashboard");
  const requested = params?.dashboard as DashboardKey | undefined;
  const config = requested ? dashboards[requested] : undefined;
  const [session, setSession] = useState<Session | null>(null); const [profile, setProfile] = useState<Profile | null>(null); const [assignedRoles, setAssignedRoles] = useState<InstitutionalRole[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const allowed = useMemo(() => Boolean(profile && requested && canAccessDashboard(profile.role, assignedRoles, requested)), [profile, assignedRoles, requested]);
  useEffect(() => { if (!supabaseConfigured) { setError("The NIU account connection is not configured."); setLoading(false); return; } let active = true; async function load() { const { data: sessionData } = await supabase.auth.getSession(); if (!active) return; setSession(sessionData.session); if (!sessionData.session) { setLoading(false); return; } const { data: profileData, error: profileError } = await supabase.from("profiles").select("role, display_name, legal_name").eq("id", sessionData.session.user.id).maybeSingle(); if (!active) return; if (profileError || !profileData) { setError("A role-enabled NIU profile is required for this workspace."); setLoading(false); return; } setProfile(profileData as Profile); const { data: assignments } = await supabase.from("profile_role_assignments").select("institutional_role").eq("profile_id", sessionData.session.user.id); if (!active) return; setAssignedRoles((assignments ?? []).map((item) => item.institutional_role as InstitutionalRole)); setLoading(false); } load(); return () => { active = false; }; }, []);
  if (loading) return <SiteShell><div className="mx-auto flex min-h-[55vh] flex-col items-center justify-center"><LoaderCircle className="h-8 w-8 animate-spin text-wine" /><p className="mt-4 text-sm text-ink/60">Loading role-specific workspace…</p></div></SiteShell>;
  if (!config) return <SiteShell><section className="mx-auto flex min-h-[55vh] max-w-2xl flex-col items-center justify-center px-5 text-center"><AlertCircle className="h-10 w-10 text-wine" /><h1 className="mt-5 font-serif text-4xl">Workspace not found.</h1><Link href="/portal" className="button-primary mt-7">Return to My NIU</Link></section></SiteShell>;
  if (!session) return <SiteShell><section className="mx-auto flex min-h-[55vh] max-w-2xl flex-col items-center justify-center px-5 text-center"><ShieldAlert className="h-10 w-10 text-wine" /><h1 className="mt-5 font-serif text-4xl">Sign in to access this workspace.</h1><p className="mt-3 leading-7 text-ink/65">NIU verifies identity and role before exposing role-specific academic or administrative content.</p><Link href="/signin" className="button-primary mt-7">Sign in to NIU <ArrowRight className="h-4 w-4" /></Link></section></SiteShell>;
  if (!allowed) return <SiteShell><section className="mx-auto flex min-h-[55vh] max-w-2xl flex-col items-center justify-center px-5 text-center"><ShieldAlert className="h-10 w-10 text-wine" /><h1 className="mt-5 font-serif text-4xl">Your current NIU role does not permit this workspace.</h1><p className="mt-3 leading-7 text-ink/65">Access is determined by your protected profile and role assignments. If you believe this is incorrect, contact an authorised NIU administrator.</p><Link href="/portal" className="button-primary mt-7">Return to My NIU</Link></section></SiteShell>;
  const name = profile?.display_name || profile?.legal_name || session.user.email || "NIU colleague";
  return <SiteShell><section className="border-b border-wine/10 bg-canvas"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-4 px-5 py-12 sm:px-8 md:flex-row md:items-end lg:px-12"><div><p className="eyebrow">{config.label}</p><h1 className="mt-4 font-serif text-5xl tracking-[-0.04em]">{config.title}</h1><p className="mt-3 max-w-2xl leading-7 text-ink/65">{config.description}</p></div><p className="text-sm text-ink/60">Signed in as <span className="font-semibold text-wine">{name}</span></p></div></section><section className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 lg:px-12"><div className="grid gap-5 md:grid-cols-3">{config.cards.map(({ icon: Icon, title, body }) => <article key={title} className="min-h-60 border border-wine/10 bg-white p-7 shadow-[0_16px_36px_rgba(29,25,21,0.05)]"><Icon className="h-6 w-6 text-wine" /><h2 className="mt-6 font-serif text-2xl">{title}</h2><p className="mt-3 text-sm leading-6 text-ink/65">{body}</p></article>)}</div><div className="mt-8 border border-dashed border-wine/25 bg-canvas p-8"><h2 className="font-serif text-3xl">A safe empty state is still a governed state.</h2><p className="mt-3 max-w-3xl leading-7 text-ink/65">No placeholder student, course, certificate, grade, or audit data is displayed. Authorised records populate this workspace as actual institutional activity occurs.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/operations" className="button-secondary">Institutional operations</Link>{requested === "faculty" && <Link href="/authoring" className="button-primary">Open academic authoring <ArrowRight className="h-4 w-4" /></Link>}</div></div></section></SiteShell>;
}
