import { AlertCircle, CheckCircle2, FilePlus2, LoaderCircle, ShieldAlert } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "wouter";
import SiteShell from "@/components/SiteShell";
import { supabase, supabaseConfigured } from "@/lib/supabase";

type SetupResult = { school_id: string; department_id: string; program_id: string; course_id: string; status: string; created_school: boolean; created_department: boolean; created_program: boolean; created_course: boolean };

export default function StarterProgrammeSetup() {
  const [allowed, setAllowed] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [result, setResult] = useState<SetupResult | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!supabaseConfigured) { setLoading(false); return; } let active = true; async function load() { const { data: sessionData } = await supabase.auth.getSession(); if (!active || !sessionData.session) { setLoading(false); return; } const { data: profile } = await supabase.from("profiles").select("role, account_status").eq("id", sessionData.session.user.id).maybeSingle(); if (!active) return; setAllowed(profile?.role === "super_admin" && profile.account_status === "active"); setLoading(false); } void load(); return () => { active = false; }; }, []);
  async function initialize() { if (!window.confirm("Create NIU’s recommended first school, department, certificate programme, required course link, and draft course? Nothing will be published, and no modules, lessons, learners, or materials will be created.")) return; setSaving(true); setError(null); const { data, error: setupError } = await supabase.rpc("niu_initialize_digital_starter_programme"); if (setupError) setError(setupError.message); else setResult(data as SetupResult); setSaving(false); }
  if (loading) return <SiteShell><div className="grid min-h-[55vh] place-items-center"><LoaderCircle className="h-8 w-8 animate-spin text-wine" /></div></SiteShell>;
  if (!allowed) return <SiteShell><section className="mx-auto flex min-h-[55vh] max-w-2xl flex-col items-center justify-center px-5 text-center"><ShieldAlert className="h-10 w-10 text-wine" /><h1 className="mt-5 font-serif text-4xl">Super Administrator authority required.</h1><p className="mt-3 leading-7 text-ink/65">Only an active NIU Super Administrator can initialize this institutional starter structure.</p><Link href="/portal" className="button-primary mt-7">Return to My NIU</Link></section></SiteShell>;
  return <SiteShell><section className="border-b border-wine/10 bg-canvas"><div className="mx-auto max-w-4xl px-5 py-12 sm:px-8"><p className="eyebrow">Guided institution setup</p><h1 className="mt-4 font-serif text-5xl tracking-[-0.04em]">Start NIU’s first certificate programme.</h1><p className="mt-4 max-w-3xl leading-7 text-ink/65">Create a real, controlled draft structure for NIU’s recommended programme: <strong>Digital Skills, Entrepreneurship, and Remote Work.</strong> The setup is safe to run once or again: existing matching records are retained; nothing is published; and every run is written to the NIU audit record.</p></div></section><section className="mx-auto max-w-4xl px-5 py-12 sm:px-8"><div className="border border-wine/10 bg-white p-7 shadow-[0_16px_36px_rgba(29,25,21,0.05)]"><FilePlus2 className="h-7 w-7 text-wine" /><h2 className="mt-4 font-serif text-3xl">This protected setup will create</h2><ul className="mt-5 grid gap-3 text-sm leading-6 text-ink/70"><li><strong>School:</strong> School of Digital Learning and Enterprise — draft.</li><li><strong>Department:</strong> Department of Digital Skills and Enterprise — draft.</li><li><strong>Certificate programme:</strong> Certificate in Digital Skills, Entrepreneurship, and Remote Work — draft.</li><li><strong>First required course:</strong> Digital Foundations for Enterprise and Remote Work — draft, with version 1.</li></ul><p className="mt-6 border-l-4 border-gold bg-gold/10 p-4 text-sm leading-6 text-ink/80">It will not create modules, lessons, notes, tests, learners, payments, or public listings. You will add and review those later before the existing programme-package quality gate permits publication.</p>{error && <p role="alert" className="mt-5 flex gap-2 border-l-4 border-wine bg-wine/5 p-4 text-sm"><AlertCircle className="h-5 w-5 shrink-0 text-wine" />{error}</p>}{result ? <div className="mt-6 border-l-4 border-emerald-700 bg-emerald-50 p-5 text-emerald-950"><div className="flex gap-2"><CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-700" /><p className="font-semibold">NIU’s controlled starter structure is ready as draft records.</p></div><p className="mt-2 text-sm leading-6">Next, use the Module Blueprint to add your real modules, then create lessons and upload only approved protected materials. Publication remains blocked until all readiness checks pass.</p><div className="mt-4 flex flex-wrap gap-3"><Link href="/module-blueprint" className="button-primary">Plan modules</Link><Link href="/programme-package" className="border border-wine px-4 py-2 text-sm font-bold text-wine">Open programme package</Link></div></div> : <button onClick={initialize} disabled={saving} className="button-primary mt-7 disabled:opacity-60">{saving ? "Creating protected draft structure…" : "Create protected starter structure"}</button>}</div></section></SiteShell>;
}
