import { describe, expect, it } from "vitest";
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(__dirname, "..");
const router = fs.readFileSync(path.join(root, "server", "routers", "aiBuilder.ts"), "utf8");
const orchestrator = fs.readFileSync(path.join(root, "server", "aiOrchestrator.ts"), "utf8");
const migration = fs.readFileSync(path.join(root, "docs", "supabase", "20260827_niu_ai_academic_builder.sql"), "utf8");
const governanceMigration = fs.readFileSync(path.join(root, "docs", "supabase", "20260827_niu_ai_academic_builder_governance.sql"), "utf8");
const reviewMigration = fs.readFileSync(path.join(root, "docs", "supabase", "20260827_niu_ai_academic_builder_review.sql"), "utf8");
const generationMigration = fs.readFileSync(path.join(root, "docs", "supabase", "20260827_niu_ai_academic_builder_generation.sql"), "utf8");
const packageMigration = fs.readFileSync(path.join(root, "docs", "supabase", "20260828_niu_ai_draft_package_rpc.sql"), "utf8");
const visualMigration = fs.readFileSync(path.join(root, "docs", "supabase", "20260828_niu_ai_visual_assets.sql"), "utf8");
const page = fs.readFileSync(path.join(root, "client", "src", "pages", "AIAcademicBuilder.tsx"), "utf8");
const clientMain = fs.readFileSync(path.join(root, "client", "src", "main.tsx"), "utf8");
const app = fs.readFileSync(path.join(root, "client", "src", "App.tsx"), "utf8");
const packagePage = fs.readFileSync(path.join(root, "client", "src", "pages", "ProgrammePackage.tsx"), "utf8");
const dashboard = fs.readFileSync(path.join(root, "client", "src", "pages", "AdminDashboard.tsx"), "utf8");

describe("NIU AI Academic Builder", () => {
  it("stores only a staff-authorized staged planning job", () => {
    expect(migration).toContain("create table if not exists public.ai_academic_builder_jobs");
    expect(migration).toContain("status text not null default 'draft'");
    expect(migration).toContain("public.niu_is_academic_staff()");
    expect(migration).toContain("ai_academic_builder_jobs_audit");
    expect(governanceMigration).toContain("niu_validate_ai_academic_builder_status");
    expect(governanceMigration).toContain("AI Builder status transition");
    expect(governanceMigration).toContain("Administrator authorization is required");
    expect(governanceMigration).toContain("Published AI Builder jobs can only be archived");
    expect(router).toContain("Academic staff authority is required");
    expect(router).toContain("No academic records were created");
    expect(router).toContain("Sources must use HTTPS URLs");
    expect(router).toContain("submitResearchReview");
    expect(reviewMigration).toContain("research_sources");
    expect(reviewMigration).toContain("research notes of at least 20 characters");
    expect(router).toContain("generateReviewPlans");
    expect(router).toContain("handoffToCurriculumImport");
    expect(router).toContain("curriculum_imports");
    expect(router).toContain("status: \"ready_for_review\"");
    expect(generationMigration).toContain("assessment_blueprint");
    expect(generationMigration).toContain("visual_plan");
    expect(generationMigration).toContain("research_evidence");
    expect(packageMigration).toContain("niu_create_ai_draft_package");
    expect(packageMigration).toContain("'draft',actor");
    expect(packageMigration).toContain("lesson_content_items");
    expect(packageMigration).toContain("assessment_questions");
    expect(packageMigration).toContain("generated_record_ids");
    expect(packageMigration).toContain("videoScript");
    expect(packageMigration).toContain("transcript");
    expect(packageMigration).toContain("Missing: administrator must author a video script");
    expect(packageMigration).toContain("Missing: administrator must define and approve a rubric");
    expect(router).toContain("generateCompletePackage");
    expect(router).toContain("governed draft-package generator");
  });

  it("uses explicit structured planning and never fabricates sources or difficulty values", () => {
    expect(router).toContain("Do not invent references, research findings");
    expect(router).toContain("introductory",);
    expect(router).toContain("intermediate");
    expect(router).toContain("advanced");
    expect(router).toContain('provider: "gemini"');
    expect(router).toContain("generationDepth");
    expect(router).toContain("validateBlueprint");
    expect(router).toContain('providerHealth("gemini")');
    expect(router).toContain("geminiConfigured");
    expect(router).toContain("selectedModelAvailable");
    expect(orchestrator).toContain("value.toUpperCase()");
    expect(orchestrator).toContain("providerHealth");
    expect(router).toContain("runStructuredAIWithFallback");
    expect(router).not.toContain("invokeLLM");
    expect(router).toContain("schema: blueprintSchema");
    expect(router).toContain("AI provider is not configured.");
    expect(router).toContain("AI provider request failed.");
    expect(router).toContain("AI returned invalid structured data.");
    expect(router).toContain("researchPlan");
    expect(router).toContain("missingInformation");
    expect(router).toContain("runQualityGate");
    expect(router).toContain("source-provenance");
    expect(router).toContain("curriculum-completeness");
    expect(router).toContain("duplicate-content");
    expect(router).toContain("accessibility");
    expect(router).toContain("certificate-configuration");
    expect(router).toContain("publication-boundary");
    expect(router).toContain("learnerPreview");
    expect(page).toContain("Answer keys and administrator controls are intentionally excluded");
    expect(page).toContain("Run complete-package quality gate");
    expect(page).toContain("Open read-only learner preview");
  });

  it("keeps generated visuals private, accessible, versioned, and linked to exact lessons", () => {
    expect(visualMigration).toContain("create table if not exists public.ai_visual_asset_versions");
    expect(visualMigration).toContain("alt_text text not null");
    expect(visualMigration).toContain("review_status text not null default 'draft'");
    expect(visualMigration).toContain("enable row level security");
    expect(router).toContain("generateVisualSpecifications");
    expect(router).toContain("generateVisualAssets");
    expect(router).toContain("is_generated_visual: true");
    expect(router).toContain('status: "draft"');
    expect(router).toContain("contains(\"visual_metadata\"");
    expect(router).toContain("lesson_content_items");
    expect(router).toContain("Academic and accessibility review is required");
    expect(router).toContain("updateVisualAssetVersion");
    expect(router).toContain("listVisualAssets");
    expect(router).toContain("removeVisualDraft");
    expect(router).toContain("regenerateVisualAsset");
    expect(router).toContain("Regenerated from visual version");
    expect(router).toContain("maximum of three generation attempts");
    expect(router).toContain("last_generation_error");
    expect(router).toContain("Generate at most 12 visual drafts per administrator action");
    expect(router).toContain("generation_attempts: 1");
    expect(visualMigration).toContain("generation_attempts integer not null default 0");
    expect(visualMigration).toContain("visual_generation_status text not null default 'not_started'");
    expect(visualMigration).toContain("visual_generation_cursor integer not null default 0");
    expect(router).toContain("visual_generation_status: \"running\"");
    expect(router).toContain("visual_generation_cursor: assetIndex + 1");
    expect(router).toContain("Only generated visual drafts can be removed here.");
    expect(router).toContain("Published or archived visual versions are immutable");
    expect(router).toContain("Required visuals are approved before publication");
    expect(router).toContain("approvedVisuals >= requiredVisuals");
    expect(packageMigration).toContain("created_lessons_json");
    expect(page).toContain("Analyse purposeful lesson visuals");
    expect(page).toContain("Generate linked visual drafts");
    expect(page).toContain("Alt text:");
    expect(page).toContain("Save metadata");
    expect(page).toContain("Regenerate draft");
    expect(clientMain).toContain("content-type");
    expect(clientMain).toContain("AI provider request failed.");
    expect(clientMain).toContain("new Response(JSON.stringify");
  });

  it("keeps the workspace review-first and reachable from the guided package", () => {
    expect(app).toContain('const AIAcademicBuilder = lazy(() => import("./pages/AIAcademicBuilder"));');
    expect(app).toContain('<Route path="/ai-academic-builder" component={AIAcademicBuilder} />');
    expect(app).toContain('<Route path="/admin/academic-ai" component={AIAcademicBuilder} />');
    expect(packagePage).toContain('href="/ai-academic-builder"');
    expect(dashboard).toContain('["NIU AI Academic Builder", "/ai-academic-builder"]');
    expect(page).toContain("Generate Complete Programme Plan");
    expect(page).toContain("No course, lesson, question, assessment, material, or certificate record is generated at this stage");
    expect(page).toContain("Review the research plan");
    expect(page).toContain("Generate Complete Academic Package");
    expect(page).toContain("Starter — architecture and titles");
    expect(page).toContain("Premium — complete notes, assessments, and rules");
    expect(page).toContain("never approves or publishes them");
  });
});
